# Application Configuration
quarkus:
  application:
    name: product-catalog-service
    version: 1.0.0
  
  # HTTP Configuration
  http:
    port: 8083
    host: 0.0.0.0
    cors:
      ~: true
      origins: "*"
      headers: "*"
      methods: "*"
  
  # Database Configuration
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/product_catalog
    username: postgres
    password: postgres
    
  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true
      format-sql: true
    jdbc:
      timezone: Asia/Tokyo
  
  # Flyway Configuration
  flyway:
    migrate-at-start: true
    locations: classpath:db/migration
    
  # OpenAPI Configuration
  smallrye-openapi:
    info-title: Product Catalog Service API
    info-version: 1.0.0
    info-description: スキー用品ショップ 商品カタログサービス API
    info-contact-email: dev@ski-shop.com
    servers:
      - url: http://localhost:8083
        description: Local development
  
  # Health Configuration
  smallrye-health:
    root-path: /q/health
    
  # Metrics Configuration
  micrometer:
    export:
      prometheus:
        enabled: true
        path: /q/metrics
        
  # Logging Configuration
  log:
    level: INFO
    category:
      "com.ski.shop":
        level: DEBUG
      "org.hibernate.SQL":
        level: DEBUG
      "org.hibernate.type.descriptor.sql.BasicBinder":
        level: TRACE
    console:
      enable: true
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n"
      
  # Cache Configuration
  cache:
    caffeine:
      products:
        maximum-size: 1000
        expire-after-write: PT10M
      categories:
        maximum-size: 100
        expire-after-write: PT1H
        
  # Banner
  banner:
    enabled: true
    path: banner.txt

# Custom Application Properties
app:
  product:
    image:
      base-url: "https://images.ski-shop.com"
      max-size: 5MB
    search:
      max-results: 100
      default-page-size: 20
  category:
    max-depth: 5
  brand:
    featured-limit: 20

---
# Development Profile
"%dev":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:postgresql://localhost:5432/product_catalog_dev
    hibernate-orm:
      database:
        generation: validate
    log:
      level: DEBUG

---
# Test Profile
"%test":
  quarkus:
    datasource:
      db-kind: h2
      jdbc:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ""
    hibernate-orm:
      database:
        generation: drop-and-create
      sql-load-script: import-test.sql
    log:
      level: WARNING
      category:
        "com.ski.shop":
          level: DEBUG

---
# Production Profile
"%prod":
  quarkus:
    datasource:
      jdbc:
        url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/product_catalog}
      username: ${DATABASE_USERNAME:postgres}
      password: ${DATABASE_PASSWORD:postgres}
    hibernate-orm:
      database:
        generation: validate
      sql-load-script: no-file
    log:
      level: INFO
      category:
        "com.ski.shop":
          level: INFO
        "org.hibernate.SQL":
          level: WARNING
        "org.hibernate.type.descriptor.sql.BasicBinder":
          level: WARNING
    smallrye-openapi:
      servers:
        - url: https://api.ski-shop.com
          description: Production
