global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'shopping-cart-service'
    static_configs:
      - targets: ['cart-service:8088']
    metrics_path: '/metrics'
    scrape_interval: 30s
